apiVersion: v2
appVersion: "1"
dependencies:
  - name: bplibchart
    repository: file://../../common/helm-charts
    version: 0.1.0
description: A Helm chart for tailrix example playground
icon: https://raw.githubusercontent.com/jenkins-x/jenkins-x-platform/d273e09/images/go.png
name: tailrix-exp-playground
version: 0.1.0
