name: Release Charts

on:
  workflow_call:
  workflow_dispatch:
  release:
    types: [published]

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Install Helm
        uses: azure/setup-helm@v3
        with:
          version: "v3.6.3" # default is latest (stable)
        id: install

      - name: build the charts
        run: |
          export URLBASE=https://tailrix.github.io/helm-charts
          cd deployments
          pip3 install -r scripts/requirements.txt
          python3 scripts/release_helmchart.py ./ $URLBASE --build-all
        shell: bash

      - name: Pushes to another repository
        uses: fredrikluo/github-action-push-to-another-repository@main
        env:
          SSH_DEPLOY_KEY: ${{ secrets.BP_RELEASE_CHART }}
        with:
          source-directory: "deployments/.build"
          destination-github-username: "tailrix"
          destination-repository-name: "helm-charts"
          user-email: bot@bp.com
          target-branch: main
          post-process-cmd: "helm repo index ."
